FROM quay.io/fedora/fedora@sha256:b512e3a77d58ace885c89d9dc87c5584ea799360c46a6cc21d167270ba1a0b85 AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install dnf-plugins-core git efivar-libs efivar-devel python3-jinja2 python3-PyMySQL python3-psycopg2 nc && dnf -y builddep tpm2-tools
RUN git clone -b 5.7 https://github.com/tpm2-software/tpm2-tools.git && \
    cd tpm2-tools && \
    git config user.email "main@keylime.groups.io" && \
    git config user.name "Keylime" && \
    ./bootstrap && \
    ./configure && \
    make && make install && \
    cd .. && rm -rf tpm2-tools
