FROM quay.io/fedora/fedora@sha256:679a99d29ed2d1b065438632aa3fa8e7da8944fc46db60962e340d23670c4402 AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install dnf-plugins-core git efivar-libs efivar-devel && dnf -y builddep tpm2-tools 
RUN git clone -b 5.7 https://github.com/tpm2-software/tpm2-tools.git && \
    cd tpm2-tools && \
    git config user.email "main@keylime.groups.io" && \
    git config user.name "Keylime" && \
    ./bootstrap && \
    ./configure && \
    make && make install && \
    cd .. && rm -rf tpm2-tools

ENV GOPATH=/root/go
RUN --mount=target=/keylime,type=bind,source=.,rw \
    cd /keylime && ./installer.sh -o && \
    dnf -y install python3-PyMySQL
