FROM quay.io/fedora/fedora@sha256:78864f98cc2fd1287e92abd2ab2264c23462c3b2e89ffab4f2c1f76219a70f96 AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install \
    awk \
    dnf-plugins-core \
    efivar-devel \
    efivar-libs \
    git \
    nc \
    python3-PyMySQL \
    python3-jinja2 \
    python3-psycopg2 \
    tpm2-tools
